global:
  resolve_timeout: 2h
route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'slack'
receivers:
  - name: 'slack'
    slack_configs:
      - api_url: "https://hooks.slack.com/services/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"
        channel: "#alert-test"
        text: "Alert!"
        title: "{{.CommonAnnotations.summary}}"