global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: 'email'
receivers:
  - name: 'email'
    email_configs:
    - to: 'chenhung0506@gmail.com'
      from: 'chenhunglin@emotibot.com'
      smarthost: smtp.partner.outlook.cn:587
      auth_username: 'chenhunglin@emotibot.com'
      auth_identity: 'chenhunglin@emotibot.com'
      auth_password: 'chenhunglin@Emotibot'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
